
// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;

namespace SampleImageClassification.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            var imageBytes = File.ReadAllBytes(@"C:\Users\lerha\OneDrive\Masaüstü\YNCTFv2WF\YNCTFv2WF\Images\AHatasi\1.png");
            SampleImageClassification.ModelInput sampleData = new SampleImageClassification.ModelInput()
            {
                ImageSource = imageBytes,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = SampleImageClassification.Predict(sampleData);
            Console.WriteLine($"\n\nPredicted Label value: {predictionResult.PredictedLabel} \nPredicted Label scores: [{String.Join(",", predictionResult.Score)}]\n\n");
        }
    }
}

